stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.before_app_script: &before_app_script
  - whoami
  - id
  - pwd
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

deploy:
  stage: deploy
  only:
    - master
  script:
    - *before_app_script
    - npm install --prefix frontend
    - npm run build --prefix frontend
    - export ENV=production
    - chmod +x ./scripts/restart.sh
    - ./scripts/restart.sh
  environment:
    name: production
    url: http://146.169.40.72:8000

